### ISSUE TITLE
add '//' patterns as malicious ?

### ISSUE THREAD

**Issue by jeromew** [koajs/send#10]
I wonder what you think about adding a sequence of consecutive slashes as potentially malicious.

maybe finding '//' in the path should throw ?

**Comment by chatoo2412** [comment]
But, it is malicious in koa-send v5.0.0 :(

```ts
import path from 'path';
import Koa from 'koa';
import serve from 'koa-static';

const koa = new Koa();

koa.use(serve(path.resolve(__dirname, '../static')));

koa.listen(3000);
```

```
{ BadRequestError: Malicious Path
    at resolvePath (/path/to/project/node_modules/resolve-path/index.js:80:11)
    at send (/path/to/project/node_modules/koa-send/index.js:68:10)
    at koa.use (/path/to/project/src/server/index.ts:21:22)
    at dispatch (/path/to/project/node_modules/koa-compose/index.js:42:32)
    at koa.use (/path/to/project/src/server/index.ts:10:11)
    at dispatch (/path/to/project/node_modules/koa-compose/index.js:42:32)
    at /path/to/project/node_modules/koa-compose/index.js:34:12
    at Application.handleRequest (/path/to/project/node_modules/koa/lib/application.js:151:12)
    at Server.handleRequest (/path/to/project/node_modules/koa/lib/application.js:133:19)
    at Server.emit (events.js:182:13) message: 'Malicious Path' }
```
