### ISSUE TITLE
Test "when path does not finish with slash and format is enabled should 200" fails

### ISSUE THREAD

**Issue by felixfbecker** [koajs/send#34]
```
1) send(ctx, file) when path does not finish with slash and format is enabled should 200:
     Error: Parse Error
      at Error (native)
      at Socket.socketOnData (_http_client.js:305:20)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)
```
The issue is that in index.js:73 fs.stat() is called, checked for a directory and then the index is appended to the path. However, fs.stat() isn't called again, so stat.size is 0, which means Content-Length is set wrong and therefor a Parse Error is emitted. PR incoming.

**Comment by felixfbecker** [comment]
Btw I have no idea why this wasn't picked up by Travis but it's an obvious bug and the test failed on my machine (Linux). I went through it with a debugger and saw that Content-Length was being set to 0, while doing fs.stat() in REPL yielded 10.
