### ISSUE TITLE
Warning: a promise was created in a handler but was not returned from it

### ISSUE THREAD

**Issue by maximilianmikus** [koajs/send#47]
I am receiving this warning:
`Warning: a promise was created in a handler but was not returned from it`

the file is served properly though.

I used koa-convert to use koa-static with koa alpha 3:
```
app.use(convert(serve(__dirname + '../../../dist', { maxage: config.cacheTime })));
```

npm versions:
```
"koa": "^2.0.0-alpha.3",
"koa-send": "^3.1.0",
"koa-static": "^1.5.2",
"koa-convert": "^1.2.0",
```

```
koa-send send "/" {"maxage":604800000,"root":"/home/max/projects/kask/dist","index":"index.html"} +12s
Warning: a promise was created in a handler but was not returned from it
    at Object.eval (eval at <anonymous> (/home/max/projects/kask/node_modules/thenify/index.js:30:15), <anonymous>:9:8)
    at Object.<anonymous> (/home/max/projects/kask/node_modules/koa-static/node_modules/koa-send/index.js:72:28)
    at [object Generator].next (native)
    at onFulfilled (/home/max/projects/kask/node_modules/co/index.js:65:19)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at next (/home/max/projects/kask/node_modules/co/index.js:100:51)
    at onFulfilled (/home/max/projects/kask/node_modules/co/index.js:69:7)
    at /home/max/projects/kask/node_modules/co/index.js:54:5
    at Object.co (/home/max/projects/kask/node_modules/co/index.js:50:10)
    at Object.toPromise (/home/max/projects/kask/node_modules/co/index.js:118:63)
    at next (/home/max/projects/kask/node_modules/co/index.js:99:29)
    at onFulfilled (/home/max/projects/kask/node_modules/co/index.js:69:7)
    at /home/max/projects/kask/node_modules/co/index.js:54:5
    at Object.co (/home/max/projects/kask/node_modules/co/index.js:50:10)
    at converted (/home/max/projects/kask/node_modules/koa-convert/index.js:17:15)
    at dispatch (/home/max/projects/kask/node_modules/koa/node_modules/koa-compose/index.js:41:32)
    at next (/home/max/projects/kask/node_modules/koa/node_modules/koa-compose/index.js:42:18)
    at /home/max/projects/kask/node_modules/koa-bodyparser/index.js:60:14
    at process._tickCallback (node.js:377:9)
```

**Comment by coderhaoxin** [comment]
https://github.com/koajs/static/issues/62

**Comment by tejasmanohar** [comment]
https://github.com/tj/co/pull/256#issuecomment-168475913

**Comment by tejasmanohar** [comment]
not really an issue with koa-static
