### ISSUE TITLE
Unexpected token function

### ISSUE THREAD

**Issue by justjoker** [koajs/send#77]
**use koa-views and koa-view use koa-sen** 
Start File:
```
require('babel-core/register');
require('babel-polyfill');
const app = require('../app.js');
```
.babelrc File
```
{
  "presets": [
    "es2015-node",
    "stage-3"
  ],
  "plugins": [
    "add-module-exports"
  ]
}
```
app File
```
import Koa from 'koa';
import views from 'koa-views';
const app = new Koa();
```

Error 

/Volumes/Mac/Projects/Node/koa-test/node_modules/koa-send/index.js:37
async function send (ctx, path, opts = {}) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Volumes/Mac/Projects/Node/koa-test/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/Mac/Projects/Node/koa-test/node_modules/koa-views/src/index.js:8:14)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Volumes/Mac/Projects/Node/koa-test/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by coderhaoxin** [comment]
you need `node >= 7.6.0` or add `babel-plugin-transform-async-to-generator` :)
